# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R-BvMpDP_LB7_t35xseb9IbALmQDBYam
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6])
y=np.array([0,250])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,2,4,6])
y=np.array([8,1,7,2])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,0,5,5])
y=np.array([0,35,35,0])
mycolor=['red','green','yellow','purple']
size=[50,100,150,200]
plt.scatter(x,y,color=mycolor)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['680','681'])
y=np.array([25,23])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([90,95,95,90])
mylabels=["suniy intelekt","kompyuterni tashkil etish","elektronika","malumotlar tuzilmasi"]
plt.pie(x, labels=mylabels)
plt.show

import matplotlib.pyplot as plt
import numpy as np
x=np.array([90,95,95,90])
mylabels=["suniy intelekt","kompyuterni tashkil etish","elektronika","malumotlar tuzilmasi"]
myexplode = [0.2,0,0,0]
plt.pie(x, labels=mylabels, startangle=90, explode=myexplode)
plt.show